from django.db import models

MOVE_COMMAND = "MOVE"
TAKE_COMMAND = "TAKE"
OPEN_COMMAND = "OPEN"
USE_COMMAND = "USE"

COMMAND_OPTIONS = {
    MOVE_COMMAND: [MOVE_COMMAND, "GO", "EXPLORE", "ENTER", "LEAVE"],
    TAKE_COMMAND: [TAKE_COMMAND],
    OPEN_COMMAND: [OPEN_COMMAND],
    USE_COMMAND: [USE_COMMAND],
}

ALL_COMMANDS = sum(COMMAND_OPTIONS.values(), start=[])
