from django.db import models

MOVE_COMMAND = "MOVE"
TAKE_COMMAND = "TAKE"
DROP_COMMAND = "DROP"
OPEN_COMMAND = "OPEN"

COMMAND_OPTIONS = {
    MOVE_COMMAND: [MOVE_COMMAND, "GO", "EXPLORE", "ENTER", "LEAVE"],
    TAKE_COMMAND: [TAKE_COMMAND],
    DROP_COMMAND: [DROP_COMMAND, "THROW"],
    OPEN_COMMAND: [OPEN_COMMAND],
}

ALL_COMMANDS = sum(COMMAND_OPTIONS.values(), start=[])
