# Generated by Django 4.2 on 2026-02-05 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("room", "0002_room_game"),
        ("game", "0004_alter_game_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("description", models.CharField(max_length=1000)),
                (
                    "item_type",
                    models.CharField(
                        choices=[("KEY", "Key"), ("CONTAINER", "Container")],
                        max_length=20,
                    ),
                ),
                ("is_starting_item", models.BooleanField(default=False)),
                (
                    "contained_within",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contents",
                        to="item.item",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="game.game",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="room.room",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("contained_within__isnull", True),
                        ("is_starting_item", False),
                        ("room__isnull", False),
                    ),
                    models.Q(
                        ("contained_within__isnull", False),
                        ("is_starting_item", False),
                        ("room__isnull", True),
                    ),
                    models.Q(
                        ("contained_within__isnull", True),
                        ("is_starting_item", True),
                        ("room__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="must_have_one_location",
            ),
        ),
    ]
