# Generated by Django 4.2 on 2026-02-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("GENERIC", "Generic Item"),
                    ("KEY", "Key"),
                    ("CONTAINER", "Container"),
                    ("LIGHT", "Light"),
                ],
                max_length=20,
            ),
        ),
    ]
