# Generated by Django 5.2.9 on 2026-02-05 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0002_alter_item_item_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="container_is_locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="item",
            name="container_key_required",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="unlocks_containers",
                to="item.item",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("GENERIC", "Generic Item"),
                    ("KEY", "Key"),
                    ("CONTAINER", "Container"),
                    ("LIGHT", "Light Source"),
                ],
                max_length=20,
            ),
        ),
    ]
