# Generated by Django 4.2 on 2026-02-05 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0005_session"),
        ("item", "0003_item_container_is_locked_item_container_key_required_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="session",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="game.session",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="container_key_required",
            field=models.ForeignKey(
                limit_choices_to=models.Q(("item_type", "KEY")),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="unlocks_containers",
                to="item.item",
            ),
        ),
    ]
