# Generated by Django 4.2 on 2026-02-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0004_item_session_alter_item_container_key_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="in_inventory",
            field=models.BooleanField(default=False),
        ),
    ]
