# Generated by Django 5.2.9 on 2026-02-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0006_alter_session_current_location"),
        ("item", "0005_item_in_inventory"),
        ("room", "0004_exit_session_room_session"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="item",
            name="must_have_one_location",
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("session__isnull", False),
                    models.Q(
                        ("contained_within__isnull", True),
                        ("is_starting_item", False),
                        ("room__isnull", False),
                    ),
                    models.Q(
                        ("contained_within__isnull", False),
                        ("is_starting_item", False),
                        ("room__isnull", True),
                    ),
                    models.Q(
                        ("contained_within__isnull", True),
                        ("is_starting_item", True),
                        ("room__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="must_have_one_location",
            ),
        ),
    ]
