# Generated by Django 5.2.9 on 2026-02-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0006_remove_item_must_have_one_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="container_discard_after_open",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="item",
            name="container_is_open",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="item",
            name="container_open_name",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
