# Generated by Django 5.2.9 on 2026-03-04 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0015_triggerableeffect"),
        ("item", "0007_item_container_discard_after_open_and_more"),
        ("room", "0004_exit_session_room_session"),
    ]

    operations = [
        migrations.CreateModel(
            name="Puzzle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("description", models.CharField(max_length=1000)),
                ("solution", models.CharField(max_length=250)),
                ("solved_name", models.CharField(max_length=250)),
                ("solved_description", models.CharField(max_length=1000)),
                ("is_solved", models.BooleanField(default=False)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="puzzles",
                        to="game.game",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="puzzles",
                        to="room.room",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="puzzles",
                        to="game.session",
                    ),
                ),
            ],
        ),
    ]
