# Generated by Django 5.2.9 on 2026-03-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0008_puzzle"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="accepted_names",
            field=models.CharField(default="", max_length=1000),
            preserve_default=False,
        ),
    ]
