# Generated by Django 5.2.9 on 2026-03-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0009_item_accepted_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="in_room_description",
            field=models.CharField(default="", max_length=1000),
            preserve_default=False,
        ),
    ]
