# Generated by Django 5.2.9 on 2026-03-06 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0010_item_in_room_description"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="item",
            name="must_have_one_location",
        ),
    ]
