# Generated by Django 5.2.9 on 2026-04-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0011_remove_item_must_have_one_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="can_be_taken",
            field=models.BooleanField(default=True),
        ),
    ]
