# Generated by Django 5.2.9 on 2026-04-13 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0021_alter_game_base_damage_alter_player_base_damage"),
        ("item", "0012_item_can_be_taken"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="damage",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="game.damageoutput",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("GENERIC", "Generic Item"),
                    ("KEY", "Key"),
                    ("CONTAINER", "Container"),
                    ("LIGHT", "Light Source"),
                    ("WEAPON", "Weapon"),
                ],
                max_length=20,
            ),
        ),
    ]
