# Generated by Django 5.2.9 on 2026-04-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0013_item_damage_alter_item_item_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("GENERIC", "Generic"),
                    ("KEY", "Key"),
                    ("CONTAINER", "Container"),
                    ("LIGHT", "Light Source"),
                    ("WEAPON", "Weapon"),
                ],
                max_length=20,
            ),
        ),
    ]
