# Generated by Django 5.2.9 on 2026-04-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0014_alter_item_item_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="healing",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("GENERIC", "Generic"),
                    ("KEY", "Key"),
                    ("CONTAINER", "Container"),
                    ("LIGHT", "Light Source"),
                    ("WEAPON", "Weapon"),
                    ("HEALTH", "Health"),
                ],
                max_length=20,
            ),
        ),
    ]
