# Generated by Django 5.2.9 on 2026-02-04 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
        ("room", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="game",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms",
                to="game.game",
            ),
            preserve_default=False,
        ),
    ]
