# Generated by Django 5.2.9 on 2026-02-05 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0003_item_container_is_locked_item_container_key_required_and_more"),
        ("room", "0002_room_game"),
    ]

    operations = [
        migrations.AddField(
            model_name="exit",
            name="key_required",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="unlocks",
                to="item.item",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="required_items",
            field=models.ManyToManyField(
                related_name="required_by_rooms", to="item.item"
            ),
        ),
    ]
