# Generated by Django 4.2 on 2026-02-05 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0005_session"),
        ("room", "0003_exit_key_required_room_required_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="exit",
            name="session",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exits",
                to="game.session",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="session",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms",
                to="game.session",
            ),
        ),
    ]
