# Generated by Django 5.2.9 on 2026-03-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0004_exit_session_room_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="accepted_names",
            field=models.CharField(default="", max_length=1000),
            preserve_default=False,
        ),
    ]
