# Generated by Django 5.2.9 on 2026-03-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0005_room_accepted_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="visited",
            field=models.BooleanField(default=False),
        ),
    ]
