# Generated by Django 5.2.9 on 2026-04-07 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0006_room_visited"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exit",
            name="one_to_two",
        ),
        migrations.RemoveField(
            model_name="exit",
            name="two_to_one",
        ),
    ]
