# Generated by Django 5.2.9 on 2026-04-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0007_remove_exit_one_to_two_remove_exit_two_to_one"),
    ]

    operations = [
        migrations.AddField(
            model_name="exit",
            name="leave_room_1",
            field=models.CharField(default="", max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="exit",
            name="leave_room_2",
            field=models.CharField(default="", max_length=250),
            preserve_default=False,
        ),
    ]
