# Generated by Django 5.2.9 on 2026-07-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0008_exit_leave_room_1_exit_leave_room_2"),
    ]

    operations = [
        migrations.AddField(
            model_name="exit",
            name="code_required",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="exit",
            name="exit_reference",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
