# Generated by Django 5.2.9 on 2026-03-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("npc", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="enemy",
            name="accepted_names",
            field=models.CharField(default="", max_length=1000),
            preserve_default=False,
        ),
    ]
