# Generated by Django 5.2.9 on 2026-03-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("npc", "0002_enemy_accepted_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="enemy",
            name="in_room_description",
            field=models.CharField(default="", max_length=1000),
            preserve_default=False,
        ),
    ]
