# Generated by Django 5.2.9 on 2026-03-06 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0017_remove_triggerableeffect_effects_locked_and_more"),
        ("npc", "0003_enemy_in_room_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="enemydrop",
            name="game",
            field=models.ForeignKey(
                default=4,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enemy_drops",
                to="game.game",
            ),
            preserve_default=False,
        ),
    ]
