# Generated by Django 5.2.9 on 2026-03-06 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0017_remove_triggerableeffect_effects_locked_and_more"),
        ("item", "0011_remove_item_must_have_one_location"),
        ("npc", "0004_enemydrop_game"),
    ]

    operations = [
        migrations.AddField(
            model_name="friend",
            name="accepted_names",
            field=models.CharField(default="", max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="friend",
            name="in_room_description",
            field=models.CharField(default="", max_length=1000),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="FriendGift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("already_gifted", models.BooleanField(default=False)),
                (
                    "friend",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gifts",
                        to="npc.friend",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friend_gifts",
                        to="game.game",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friend_gifts",
                        to="item.item",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friend_drops",
                        to="game.session",
                    ),
                ),
            ],
        ),
    ]
