# Generated by Django 5.2.9 on 2026-03-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("npc", "0005_friend_accepted_names_friend_in_room_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="friend",
            name="dialogue",
            field=models.CharField(default="", max_length=1000),
            preserve_default=False,
        ),
    ]
