# Generated by Django 5.2.9 on 2026-03-09 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0011_remove_item_must_have_one_location"),
        ("npc", "0006_friend_dialogue"),
        ("room", "0006_room_visited"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enemydrop",
            name="item",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enemy_drop",
                to="item.item",
            ),
        ),
        migrations.AlterField(
            model_name="friend",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="friends",
                to="room.room",
            ),
        ),
        migrations.AlterField(
            model_name="friendgift",
            name="item",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="friend_gift",
                to="item.item",
            ),
        ),
    ]
