# Generated by Django 5.2.9 on 2026-03-11 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0017_remove_triggerableeffect_effects_locked_and_more"),
        ("npc", "0007_alter_enemydrop_item_alter_friend_room_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FriendDialogueOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=1000)),
                ("talking_point", models.CharField(max_length=250)),
                ("already_spoken", models.BooleanField(default=False)),
                (
                    "friend",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dialogue_options",
                        to="npc.friend",
                    ),
                ),
                (
                    "requires_dialogue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_options",
                        to="npc.frienddialogueoption",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friend_dialogue_options",
                        to="game.session",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="friendgift",
            name="dialogue_option",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gifts",
                to="npc.frienddialogueoption",
            ),
        ),
    ]
