# Generated by Django 5.2.9 on 2026-03-11 13:36

from django.db import migrations


def move_dialogue_to_dialogue_options(apps, schema):
    Friend = apps.get_model("npc", "Friend")
    FriendGift = apps.get_model("npc", "FriendGift")
    FriendDialogueOption = apps.get_model("npc", "FriendDialogueOption")

    for friend in Friend.objects.all():
        dialogue = FriendDialogueOption.objects.create(
            friend=friend,
            text=friend.dialogue,
            session=friend.session,
        )
        friend.gifts.update(dialogue_option=dialogue)


def reverse_dialogue_options(apps, schema):
    Friend = apps.get_model("npc", "Friend")
    FriendDialogueOption = apps.get_model("npc", "FriendDialogueOption")

    for dialogue in FriendDialogueOption.objects.filter(
        requires_dialogue=None, talking_point=None
    ):
        friend = dialogue.friend
        friend.dialogue = dialogue.text
        friend.save()

        dialogue.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("npc", "0008_frienddialogueoption_friendgift_dialogue_option"),
    ]

    operations = [
        migrations.RunPython(
            move_dialogue_to_dialogue_options,
            reverse_dialogue_options,
        )
    ]
