# Generated by Django 5.2.9 on 2026-03-11 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("npc", "0009_migrate_dialogue_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="friend",
            name="dialogue",
        ),
        migrations.AlterField(
            model_name="friendgift",
            name="dialogue_option",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gifts",
                to="npc.frienddialogueoption",
            ),
        ),
    ]
