# Generated by Django 5.2.9 on 2026-04-07 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("npc", "0010_remove_friend_dialogue_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="friendgift",
            name="dialogue_option",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gifts",
                to="npc.frienddialogueoption",
            ),
        ),
    ]
