# Generated by Django 5.2.9 on 2026-04-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("npc", "0011_alter_friendgift_dialogue_option"),
    ]

    operations = [
        migrations.AddField(
            model_name="frienddialogueoption",
            name="can_back_out",
            field=models.BooleanField(default=True),
        ),
    ]
