# Generated by Django 5.2.9 on 2026-04-07 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0012_item_can_be_taken"),
        ("npc", "0012_frienddialogueoption_can_back_out"),
    ]

    operations = [
        migrations.AlterField(
            model_name="friendgift",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="friend_gift",
                to="item.item",
            ),
        ),
    ]
