# Generated by Django 5.2.9 on 2026-04-09 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0017_remove_triggerableeffect_effects_locked_and_more"),
        ("item", "0012_item_can_be_taken"),
        ("npc", "0013_alter_friendgift_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="frienddialogueoption",
            name="is_hidden",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="FriendAcceptsItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("received", models.BooleanField(default=False)),
                (
                    "friend",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items_accepted",
                        to="npc.friend",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friend_items_accepted",
                        to="game.game",
                    ),
                ),
                (
                    "hides_dialogue",
                    models.ManyToManyField(
                        related_name="hidden_by", to="npc.frienddialogueoption"
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accepted_by_friend",
                        to="item.item",
                    ),
                ),
                (
                    "reveals_dialogue",
                    models.ManyToManyField(
                        related_name="revealed_by", to="npc.frienddialogueoption"
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friend_accepts_items",
                        to="game.session",
                    ),
                ),
            ],
        ),
    ]
