# Generated by Django 5.2.9 on 2026-04-13 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0012_item_can_be_taken"),
        ("npc", "0014_frienddialogueoption_is_hidden_friendacceptsitem"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="friendacceptsitem",
            unique_together={("friend", "item")},
        ),
    ]
