# Generated by Django 5.2.9 on 2026-04-13 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0019_damageoutput_game_base_damage_player_base_damage"),
        ("npc", "0015_alter_friendacceptsitem_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="enemy",
            name="damage",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="game.damageoutput",
            ),
        ),
        migrations.AddField(
            model_name="enemy",
            name="health",
            field=models.IntegerField(default=100),
        ),
    ]
