# Generated by Django 5.2.9 on 2026-04-13 14:16

from django.db import migrations


def add_default_damage(apps, schema):
    Enemy = apps.get_model("npc", "Enemy")
    DamageOutput = apps.get_model("game", "DamageOutput")
    for enemy in Enemy.objects.all():
        enemy.damage = DamageOutput.objects.create(min_damage=10, max_damage=10)
        enemy.save()


class Migration(migrations.Migration):

    dependencies = [
        ("npc", "0016_enemy_damage_enemy_health"),
        ("game", "0020_add_damages"),
    ]

    operations = [migrations.RunPython(add_default_damage, migrations.RunPython.noop)]
