# Generated by Django 5.2.9 on 2026-04-13 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0021_alter_game_base_damage_alter_player_base_damage"),
        ("npc", "0017_add_damage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enemy",
            name="damage",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="game.damageoutput"
            ),
        ),
    ]
