# Generated by Django 5.2.9 on 2026-04-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("npc", "0018_alter_enemy_damage"),
    ]

    operations = [
        migrations.AddField(
            model_name="enemy",
            name="current_health",
            field=models.IntegerField(default=0),
        ),
    ]
