# Generated by Django 5.2.9 on 2026-04-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("npc", "0019_enemy_current_health"),
    ]

    operations = [
        migrations.AddField(
            model_name="enemy",
            name="auto_fight",
            field=models.BooleanField(default=True),
        ),
    ]
