# Generated by Django 5.2.9 on 2026-04-21 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0023_player_current_health"),
        ("npc", "0020_enemy_auto_fight"),
    ]

    operations = [
        migrations.CreateModel(
            name="FriendNameChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("new_name", models.CharField(max_length=250)),
                ("new_accepted_names", models.CharField(max_length=1000)),
                ("new_description", models.CharField(max_length=1000)),
                ("new_in_room_description", models.CharField(max_length=1000)),
                ("already_changed", models.BooleanField(default=False)),
                (
                    "dialogue_option",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="name_change",
                        to="npc.frienddialogueoption",
                    ),
                ),
                (
                    "friend",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="name_changes",
                        to="npc.friend",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friend_name_changes",
                        to="game.game",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friend_name_changes",
                        to="game.session",
                    ),
                ),
            ],
        ),
    ]
