# Generated by Django 5.2.9 on 2026-04-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("npc", "0022_shopkeeper_shopkeeperitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopkeeperitem",
            name="price",
            field=models.PositiveIntegerField(),
        ),
    ]
