# Generated by Django 5.2.9 on 2026-04-24 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0027_currency_starting_amount_walletitem"),
        ("npc", "0023_alter_shopkeeperitem_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopkeeperitem",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shopkeeper_items",
                to="game.game",
            ),
        ),
    ]
