# Generated by Django 5.2.9 on 2026-04-24 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("npc", "0024_alter_shopkeeperitem_game"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopkeeperitem",
            name="shopkeeper",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="store_inventory",
                to="npc.friend",
            ),
        ),
    ]
