# Generated by Django 5.2.9 on 2026-04-24 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("npc", "0025_alter_shopkeeperitem_shopkeeper"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ShopKeeper",
        ),
    ]
