# Generated by Django 5.2.9 on 2026-02-04 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
        ("room", "0002_room_game"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="start_room",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="starts_game",
                to="room.room",
            ),
        ),
    ]
