# Generated by Django 5.2.9 on 2026-02-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_game_start_room"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="description",
            field=models.CharField(
                default="A text-based adventure game.", max_length=1000
            ),
            preserve_default=False,
        ),
    ]
