# Generated by Django 4.2 on 2026-02-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_game_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="name",
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
