# Generated by Django 4.2 on 2026-02-05 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0003_exit_key_required_room_required_items"),
        ("game", "0004_alter_game_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_location",
                    models.ForeignKey(
                        limit_choices_to=models.Q(("session__isnull", False)),
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="room.room",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="game.game",
                    ),
                ),
            ],
        ),
    ]
