# Generated by Django 4.2 on 2026-02-05 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0004_exit_session_room_session"),
        ("game", "0005_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="current_location",
            field=models.ForeignKey(
                limit_choices_to=models.Q(("session__isnull", False)),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="room.room",
            ),
        ),
    ]
