# Generated by Django 5.2.9 on 2026-02-06 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0006_alter_session_current_location"),
        ("item", "0007_item_container_discard_after_open_and_more"),
        ("room", "0004_exit_session_room_session"),
    ]

    operations = [
        migrations.CreateModel(
            name="EndState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_success", models.BooleanField(default=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="end_states",
                        to="game.game",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="room.room",
                    ),
                ),
                (
                    "owned_items",
                    models.ManyToManyField(related_name="+", to="item.item"),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="end_states",
                        to="game.session",
                    ),
                ),
            ],
        ),
    ]
