# Generated by Django 5.2.9 on 2026-02-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0007_endstate"),
    ]

    operations = [
        migrations.AddField(
            model_name="endstate",
            name="message",
            field=models.CharField(default="", max_length=1000),
            preserve_default=False,
        ),
    ]
