# Generated by Django 5.2.9 on 2026-02-09 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0008_endstate_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="endstate",
            name="session",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="end_states",
                to="game.session",
            ),
        ),
    ]
