# Generated by Django 5.2.9 on 2026-02-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0009_alter_endstate_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="endstate",
            name="name",
            field=models.CharField(default="Success!", max_length=250),
            preserve_default=False,
        ),
    ]
