# Generated by Django 5.2.9 on 2026-02-12 13:32

from django.db import migrations


def delete_existing_sessions(apps, schema):
    Session = apps.get_model("game", "Session")
    Session.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0011_game_created_by_session_player"),
    ]

    operations = [
        migrations.RunPython(delete_existing_sessions, migrations.RunPython.noop),
    ]
