# Generated by Django 5.2.9 on 2026-02-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0013_alter_session_player"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
    ]
