# Generated by Django 5.2.9 on 2026-03-04 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0014_game_is_published"),
        ("item", "0007_item_container_discard_after_open_and_more"),
        ("room", "0004_exit_session_room_session"),
    ]

    operations = [
        migrations.CreateModel(
            name="TriggerableEffect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("description", models.CharField(max_length=1000)),
                ("is_starting_quest", models.BooleanField(default=False)),
                ("is_hidden", models.BooleanField(default=False)),
                ("is_accepted", models.BooleanField(default=False)),
                ("is_achieved", models.BooleanField(default=False)),
                (
                    "effects_accepted",
                    models.ManyToManyField(
                        related_name="triggered_by", to="game.triggerableeffect"
                    ),
                ),
                (
                    "effects_locked",
                    models.ManyToManyField(
                        related_name="locked_by", to="game.triggerableeffect"
                    ),
                ),
                (
                    "exits_unlocked",
                    models.ManyToManyField(related_name="unlocked_by", to="room.exit"),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="triggerable_effects",
                        to="game.game",
                    ),
                ),
                (
                    "items_gained",
                    models.ManyToManyField(
                        related_name="gained_through", to="item.item"
                    ),
                ),
                (
                    "items_owned",
                    models.ManyToManyField(
                        related_name="effects_upon_acquisition", to="item.item"
                    ),
                ),
            ],
        ),
    ]
