# Generated by Django 5.2.9 on 2026-03-04 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0015_triggerableeffect"),
        ("item", "0008_puzzle"),
        ("room", "0004_exit_session_room_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="triggerableeffect",
            name="puzzles_solved",
            field=models.ManyToManyField(
                related_name="effects_upon_solving", to="item.puzzle"
            ),
        ),
        migrations.AddField(
            model_name="triggerableeffect",
            name="room_entered",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="effects_upon_entry",
                to="room.room",
            ),
        ),
        migrations.AddField(
            model_name="triggerableeffect",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="triggerable_effects",
                to="game.session",
            ),
        ),
    ]
