# Generated by Django 5.2.9 on 2026-03-05 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0016_triggerableeffect_puzzles_solved_and_more"),
        ("item", "0008_puzzle"),
        ("room", "0006_room_visited"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="triggerableeffect",
            name="effects_locked",
        ),
        migrations.AddField(
            model_name="triggerableeffect",
            name="item_used",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="effects_upon_use",
                to="item.item",
            ),
        ),
        migrations.AlterField(
            model_name="triggerableeffect",
            name="room_entered",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="effects_upon_entry",
                to="room.room",
            ),
        ),
    ]
