# Generated by Django 5.2.9 on 2026-04-13 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0017_remove_triggerableeffect_effects_locked_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="starting_health",
            field=models.IntegerField(default=100),
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("health", models.IntegerField()),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="game.session",
                    ),
                ),
            ],
        ),
    ]
