# Generated by Django 5.2.9 on 2026-04-13 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0018_game_starting_health_player"),
    ]

    operations = [
        migrations.CreateModel(
            name="DamageOutput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_damage", models.IntegerField()),
                ("max_damage", models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="game",
            name="base_damage",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="game.damageoutput",
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="base_damage",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="game.damageoutput",
            ),
        ),
    ]
