# Generated by Django 5.2.9 on 2026-04-13 14:16

from django.db import migrations


def add_default_damage(apps, schema):
    Game = apps.get_model("game", "Game")
    Player = apps.get_model("game", "Player")
    DamageOutput = apps.get_model("game", "DamageOutput")

    for game in Game.objects.all():
        game.base_damage = DamageOutput.objects.create(min_damage=10, max_damage=10)
        game.save()

    for player in Player.objects.all():
        player.base_damage = DamageOutput.objects.create(min_damage=10, max_damage=10)
        player.save()


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0019_damageoutput_game_base_damage_player_base_damage"),
    ]

    operations = [migrations.RunPython(add_default_damage, migrations.RunPython.noop)]
