# Generated by Django 5.2.9 on 2026-04-13 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0020_add_damages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="base_damage",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="game.damageoutput"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="base_damage",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="game.damageoutput"
            ),
        ),
    ]
