# Generated by Django 5.2.9 on 2026-04-14 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0021_alter_game_base_damage_alter_player_base_damage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="session",
            old_name="player",
            new_name="user",
        ),
        migrations.AlterField(
            model_name="player",
            name="session",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player",
                to="game.session",
            ),
        ),
    ]
