# Generated by Django 5.2.9 on 2026-04-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0022_rename_player_session_user_alter_player_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="current_health",
            field=models.IntegerField(default=0),
        ),
    ]
