# Generated by Django 5.2.9 on 2026-04-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0023_player_current_health"),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
            ],
        ),
    ]
