# Generated by Django 5.2.9 on 2026-04-24 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0025_currency_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="currency",
            name="game",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="currencies",
                to="game.game",
            ),
            preserve_default=False,
        ),
    ]
