# Generated by Django 5.2.9 on 2026-04-24 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0026_currency_game"),
    ]

    operations = [
        migrations.AddField(
            model_name="currency",
            name="starting_amount",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="WalletItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.PositiveIntegerField()),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to="game.currency",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to="game.player",
                    ),
                ),
            ],
        ),
    ]
