# Generated by Django 5.2.9 on 2026-04-24 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0027_currency_starting_amount_walletitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="currency",
            name="session",
        ),
    ]
