# Generated by Django 5.2.9 on 2026-04-24 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0028_remove_currency_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="walletitem",
            name="session",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wallet_items",
                to="game.session",
            ),
        ),
    ]
